language: objective-c
script:
  - xctool -workspace HotDaily.xcworkspace -scheme HotDaily -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace HotDaily.xcworkspace -scheme Pods-HotDailyTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
